name: MSVC build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.1

    - name: Build x64
      run: |
        mkdir x64 && cd x64
        cmake -G "Visual Studio 17 2022" -A x64 ..
        msbuild hassuttelu.sln /p:Platform=x64 /p:Configuration=Release /m

    - name: Print Hashes
      shell: pwsh
      run: |
        Get-ChildItem "x64/Release/*.exe" | Get-FileHash -Algorithm SHA256 | Format-List | Tee-Object tiivisteet.txt

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automaagikäännös"
          files: |
            tiivisteet.txt
            x64/Release/*.exe
